name: "List Trending Repos"
author: "Sarvsav"
description: "List the trending repositories on GitHub"
inputs:
  version:
    description: "set to true to list the version information"
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/sarvsav/go-list-trending-repos:latest'
  args:
    - ${{ if inputs.version == true }}:
      - '-v'
branding:
  icon: 'wifi'
  color: 'green'
