name: "List Trending Repos"
author: "Sarvsav"
description: "List the trending repositories on GitHub"
inputs:
  version:
    description: "set to true to list the version information"
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/sarvsav/go-list-trending-repos:latest'
  args:
  ## Add an if condition to run the version command if the input is set to true
  - ${{ inputs.version }}
branding:
  icon: 'wifi'
  color: 'green'
