name: "List Trending Repos"
author: "Sarvsav"
description: "List the trending repositories on GitHub"
inputs:
  version:
    description: "set to true to list the version information"
    required: false
  since:
    description: "The interval to list the trending repositories"
    required: false
    default: "daily"
outputs:
  json_data:
    description: "The JSON data output from the action"
runs:
  using: 'docker'
  image: 'docker://ghcr.io/sarvsav/go-list-trending-repos:latest'
  args:
    - ${{ inputs.version }}
    - "-s"
    - "${{ inputs.since }}"
branding:
  icon: 'wifi'
  color: 'green'
