name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - docker-release  # Specify the branches you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: make build-docker IMAGE_NAME=ghcr.io/${{ github.repository }}:latest

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest
