name: List trending Go repositories
on: [push]

jobs:
  go_list_trending_repos:
    runs-on: ubuntu-latest
    name: A job to list the trending golang repositories on GitHub
    steps:
      - name: List version information
        id: version
        uses: sarvsav/go-list-trending-repos@fb06a6d8d8778ef54edb5bf9942d50afc2af42ed
        with:
            version: true

