name: List trending Go repositories
## Add triggers on pushing to main or manually running the workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  go_list_trending_repos:
    runs-on: ubuntu-latest
    name: A job to list the trending golang repositories on GitHub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: List version information
        id: version
        uses: sarvsav/go-list-trending-repos@main
        with:
            version: -v
      - name: Generate daily report
        id: daily
        uses: sarvsav/go-list-trending-repos@main
        with:
            since: daily
      - name: Show results
        id: print
        run: |
          echo "Step outputs: ${{ toJson(steps.daily.outputs) }}"
      # - name: Generate weekly report
      #   id: weekly
      #   uses: sarvsav/go-list-trending-repos@main
      #   with:
      #       since: weekly
      # - name: Generate monthly report
      #   id: monthly
      #   uses: sarvsav/go-list-trending-repos@main
      #   with:
      #     since: monthly
      # - name: Generate complete report
      #   id: complete
      #   uses: sarvsav/go-list-trending-repos@main
      #   with:
      #       since: all