name: List trending Go repositories
on: [push]

jobs:
  go_list_trending_repos:
    runs-on: ubuntu-latest
    name: A job to list the trending golang repositories on GitHub
    steps:
      - name: List version information
        id: version
        uses: sarvsav/go-list-trending-repos@eed3e09cf6a661fe0a6db30f077102b7037988d8
        with:
            version: 'true'

